name: analyzer_app
description: A new Flutter project.

publish_to: "none"

version: 0.1.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.2
  firebase_core: ^1.11.0
  firebase_auth: ^3.3.5
  cloud_firestore: ^3.1.7
  firebase_crashlytics: ^2.5.3
  provider: ^6.0.2
  font_awesome_flutter: ^9.2.0
  another_flushbar: ^1.10.28
  flutter_svg: ^1.0.3
  flutter_spinkit: ^5.1.0
  fl_chart: ^0.46.0
  uuid: ^3.0.5
  rxdart: ^0.27.3
  package_info_plus: ^1.3.0
  google_fonts: ^2.3.1
  shared_preferences: ^2.0.13
  intl: ^0.17.0
  web_socket_channel: ^2.1.0
  avatar_glow: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  flutter_launcher_icons: "^0.9.2"

flutter_icons:
  android: true
  ios: true
  remove_alpha_ios: true
  image_path: "assets/icon/icon.png"
  adaptive_icon_background: "assets/icon/background.png"
  adaptive_icon_foreground: "assets/icon/foreground.png"

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/wave/
    - assets/theme/
